name: ps4-payload-dev

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo apt update
        sudo apt install cmake pkg-config meson clang-18 lld-18
        sudo apt install build-essential autoconf libtool yasm nasm bison flex
        sudo apt install gperf pkgconf libarchive-tools autopoint po4a git curl doxygen
        sudo apt install makepkg pacman-package-manager

    - name: Build artifacts
      run: bash ci-libs.sh

    - name: Package artifacts
      run: tar -czf ps4-payload-dev.tar.gz -C / opt/ps4-payload-sdk

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ./ps4-payload-dev.tar.gz
        if-no-files-found: error

  release:
    needs: build
    permissions:
      contents: write

    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: .

      - name: Create GitHub Release (pre-release)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          files: ps4-payload-dev.tar.gz
